In [2]:
import numpy as np

In [3]:
benimDizim = np.arange (0,15)

In [4]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
benimDizim[5]

5

In [6]:
benimDizim[3:5]

array([3, 4])

In [7]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [8]:
benimDizim[3:8]=-5

In [9]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [10]:
baskaDizi=np.arange(0,24)

In [11]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
slicingDizisi=baskaDizi[4:9]

In [13]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [14]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
slicingDizisi[:]=700

In [16]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [17]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [18]:
ornekDizi=np.arange(0,24)

In [19]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
ornekDiziKopyasi=ornekDizi.copy();

In [21]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [23]:
ornekMatrixDizisi=np.array([])

In [24]:
benimListem=[[10,20,30],[20,30,40],[40,50,60]]

In [25]:
benimMatrixDizim=np.array(benimListem)

In [26]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [27]:
benimMatrixDizim[0]

array([10, 20, 30])

In [28]:
benimMatrixDizim[1][2]

40

In [29]:
benimMatrixDizim[1,2]

40

In [30]:
benimMatrixDizim[2:,2:]

array([[60]])

In [31]:
yeniListe=[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [32]:
yeniMatrix=np.array(yeniListe)

In [33]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

## operansyonlar

In [35]:
yeniBirDizi = np.random.randint(1,100,20)

In [36]:
yeniBirDizi

array([78, 43, 29, 39, 47, 63, 95,  3, 23, 37, 79,  4, 87, 81, 96, 93, 82,
       38, 81, 69])

In [37]:
yeniBirDizi > 24

array([ True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True])

In [38]:
yeniBirDizi

array([78, 43, 29, 39, 47, 63, 95,  3, 23, 37, 79,  4, 87, 81, 96, 93, 82,
       38, 81, 69])

In [39]:
sonucDizisi = yeniBirDizi > 24

In [40]:
sonucDizisi

array([ True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True])

In [41]:
yeniBirDizi

array([78, 43, 29, 39, 47, 63, 95,  3, 23, 37, 79,  4, 87, 81, 96, 93, 82,
       38, 81, 69])

In [42]:
yeniBirDizi[sonucDizisi]

array([78, 43, 29, 39, 47, 63, 95, 37, 79, 87, 81, 96, 93, 82, 38, 81, 69])

In [43]:
yeniBirDizi

array([78, 43, 29, 39, 47, 63, 95,  3, 23, 37, 79,  4, 87, 81, 96, 93, 82,
       38, 81, 69])

In [44]:
yeniBirDizi[yeniBirDizi > 24]

array([78, 43, 29, 39, 47, 63, 95, 37, 79, 87, 81, 96, 93, 82, 38, 81, 69])

In [45]:
sonDizi = np.arange(0,24)

In [46]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [47]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [48]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [49]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [50]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [51]:
sonDizi / sonDizi

C:\Users\Root\AppData\Local\Temp/ipykernel_5664/1312094733.py:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [52]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [53]:
np.max(sonDizi)

23

In [54]:
np.min(sonDizi)

0